name: "sonarcloud scan githubActions"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=arboleda5252
            -Dsonar.projectKey=FleetGuard360-Feat1-Backend
            -Dsonar.sources=src/main/java
            -Dsonar.language=java
            -Dsonar.java.binaries=build/classes/java/main
